defaults: &defaults
  app_name: "kerker"
  domain: "http://kerker.dev"
  facebook_app_id:
  facebook_secret:
  admin_emails:
    - ""
  google_analytics_key: ""
  default_logo_url: "/logo.png"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults